### ISSUE TITLE
TODO: Temp. Voice Channels

### ISSUE THREAD

**Issue by ghost** [SUPERCHIEFYT/mosbot#1]
You can map a `setTimeout` function to delete after a specific interval and use `args[1]` to make a custom name of a voice channel. So for example the command would be: `!vcadd temp channel 60 mins` and add js cases like `days`, `hrs`, `mins`, `secs`.

Thank you,
 - Amanda

**Comment by ghost** [comment]
**__Code Reference Updates__**
[Yes] Mapped the `setTimeout` function
[No] Added js cases
[Yes] Added `args` function(s)

**Comment by RHGDEV** [comment]
**Notice**
If the duration is too long and the bot restarts, the channel will fail to remove.

**Comment by ghost** [comment]
Yes, indeed. But however you can limit the amount of time they can set for the interval, therefore you can add a watch for a specific amount of time they are obligated to set on it.

**Comment by RHGDEV** [comment]
The question is when is the bot gonna restart? We originally host on heroku. (yes **not** the best, but it's free) and it usaully restarts at random times not an exact time everyday.

Now, unless you restrict the maximum to like 1 hour to 30 mins and the bot is just about to restart it will still fail once the bot has refreshed the local db.

**Comment by ghost** [comment]
But you can store the times and channel ID's  in a MongoDB or generally a `js` config file since it's static. Here is an example of a static file:
```js
const channelModule = require('./modules/channelModule.js');
const map = {
"12345678910": "500000"
}
module.exports = map;
```

**Comment by RHGDEV** [comment]
Noooow you mention the database! Thanks for using your head!

**Comment by ghost** [comment]
Yup, silly me!!
